# Site settings
title: "PhonbireWorks"
description: "I Sell Digital Products And Services"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://phonbireworks.github.io/site" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag

# Google Analytics
google_analytics: UA-XXXXXXXX-X

# Include and Exclude files or directories from the site
include: []
exclude: ["README.md"]

# Other settings
paginate: 5
paginate_path: "/page:num/"
